apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swirl-demo-app-int
  namespace: infra
  annotations:
    swirl-demo-app.delivery/pipeline: '723'
    swirl-demo-app.delivery/source: efa776d10b2ec15148746e758340ac246fdbc1d6
    swirl-demo-app.delivery/kind: snapshot
  labels:
    app.kubernetes.io/name: swirl-demo-app
    app.kubernetes.io/part-of: swirl-demo-app
    swirl-cloud/environment: int
spec:
  project: applications-int
  source:
    repoURL: http://gitlab.swirlit.internal/swirlit/swirl-demo-app.git
    targetRevision: 49f206ced245c0d31f75c68107066ca01916a6dc
    path: infra/environments/int
  destination:
    name: in-cluster
    namespace: apps-int
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - PruneLast=true
    - FailOnSharedResource=true
