apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swirl-demo-app-int
  namespace: infra
  annotations:
    swirl-demo-app.delivery/pipeline: '780'
    swirl-demo-app.delivery/source: b33664ec934c213c6bbe0b9491363e8107cdd4e3
    swirl-demo-app.delivery/kind: snapshot
  labels:
    app.kubernetes.io/name: swirl-demo-app
    app.kubernetes.io/part-of: swirl-demo-app
    swirl-cloud/environment: int
spec:
  project: applications-int
  source:
    repoURL: http://gitlab.swirlit.internal/swirlit/swirl-demo-app.git
    targetRevision: 77fbec1cf09ececb899f516a4b2aa98fd892a9d6
    path: infra/environments/int
  destination:
    name: in-cluster
    namespace: apps-int
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    syncOptions:
    - PruneLast=true
    - FailOnSharedResource=true
